language: ruby
rvm:
  - 1.9.3

install: true

before_script:
  - ./scripts/run_sc_server.sh
  - sleep 5 # give sc-server some time to start

script: phantomjs phantomjs/test_runner.js --exclude-targets=/sproutcore/*
